### ISSUE TITLE
State Locking support

### ISSUE THREAD

**Issue by LiviusP** [ionos-cloud/terraform-provider-ionoscloud#14]
Please add support for S3 state locking

https://www.terraform.io/docs/language/state/locking.html

**Comment by worldofgeese** [comment]
@dq-peytz implemented our S3 backend to store state in IONOS' bucket. We at Famly would really like to see state locking supported.

**Comment by mflorin** [comment]
@worldofgeese @LiviusP - Not sure what we can do about that at the provider level. State locking is a core terraform feature depending only on the implementation of the S3 backend to support locking. This is not controlled by the provider - this ticket should be closed here and maybe reopened in the infrastructure queue that deals with the S3 backend we're using on our cloud.

**Comment by worldofgeese** [comment]
@mflorin I met with Paul McCutcheon at IONOS and he was able confirm that state locking has recently been implemented. A usage document was sent to me by Ev Sarny. I think this ticket is safe to close. Thank you to the IONOS team 🙏🏻.
