### ISSUE TITLE
Define the group for a user inside the user resource

### ISSUE THREAD

**Issue by jakobjoachim** [ionos-cloud/terraform-provider-ionoscloud#265]
### Current Provider Version
6.2.2

### Use-cases
It would be useful to define the group for a user inside the user resource.
Currently I have to collect all user ids from multiple modules to assign them to same group. It would be much easier (and more intuitive) to just add the group id to the user.

### Attempted Solutions
Collecting the user Ids and assigning them to the group

### Proposal
```
resource "ionoscloud_user" "example2" {
  ...
  group_id                     =  <group_id>
}
```
### References
Haven't found any.

**Comment by cristiGuranIonos** [comment]
Thanks for raising this. We like this, we were thinking of adding a list of groups in case the user needs to be a part of more than one group:
` resource "ionoscloud_user" "example2" {
  ...
  group_ids                     =  [group_id1, group_id2]
}`
