### ISSUE TITLE
Terraform integration with cloudpanel

### ISSUE THREAD

**Issue by usersina** [ionos-cloud/terraform-provider-ionoscloud#273]
### Question
Is it possible to use this module with the [cloudpanel api](https://cloudpanel-api.ionos.com/documentation/)? I got very confused at first thinking about what I might've done wrong but I later figured out that this only works with the [cloud api](https://api.ionos.com/docs/cloud/v6/).

Maybe it does work and I am still confused? I haven't found anyone mentioning this online.

**Comment by iblindu** [comment]
Hi @usersina, 

You were right, the module works only with cloud api, so unfortunately you can't use this module with the cloudpanel api.

**Comment by usersina** [comment]
Mentioning [this issue](https://github.com/ionos-cloud/terraform-provider-ionoscloud/issues/28) here for completeness purposes.
