### ISSUE TITLE
Support managing dedicated servers

### ISSUE THREAD

**Issue by p-null** [ionos-cloud/terraform-provider-ionoscloud#28]
### Current Provider Version
`v6.0.0-alpha.3`

### Use-cases
Hi, thanks for providing the IONOS cloud terraform provider! I guess this is both a question and a feature request.  

From the documentation, the `cpu_family` of `ionoscloud_server` resource are `"AMD_OPTERON", "INTEL_XEON" or "INTEL_SKYLAKE"`. However these do not include the dedicated servers' cpu family: Ryzen and EYPC. 

For `ionoscloud_volume` resource, there are only options for `SSD` and `HDD`, while for dedicated servers, the storage options include  Nvme SSD. 

Combining the above, I assume provisioning/managing dedicated servers are not supported yet. 

### Attempted Solutions

I wish I could contribute but I have limited knowledge working with terraform sdk. 

### Proposal

Support provisioning/managing dedicated servers.

I wonder if we consider using a unique identifier in the config, indicating the machine type (e.g. `AE-16-128-nvme` for the EYPC machine on this [page](https://www.ionos.ca/servers/amd-servers)). This is just an option, but the benefit of it is the user is guaranteed to provision and **billed** a machine they want. However, if we are able to use the spec to uniquely identify a machie, that works too.

**Comment by jbuchhammer** [comment]
Hi p-null,

the dedicated servers are not covered by the 'IONOS cloud' API and this plugin. Instead you can refer to the 'IONOS' Cloud Server API: https://cloudpanel-api.ionos.com/documentation/?__hstc=117056857.b3a749c396f952c47bc94d69abef6182.1624264983234.1624264983234.1624264983234.1&__hssc=117056857.4.1624264983235&__hsfp=1205546461

FYI: IONOS has two branches which originally were two companies:
- 'IONOS cloud' provides the Compute Engine (IaaS) solution (https://cloud.ionos.ca/compute?linkId=hd.products.enterpriseCloud) and where this plugin is for and 
- 'IONOS' provides VPS, Dedicated Servers, Cloud Servers and all that Domain & Hosting (https://www.ionos.ca/?linkId=hd.tab.domainHosting)

That's the reason for having two different APIs and all the confusion about 'IONOS cloud' servers and 'IONOS' Cloud Servers.
And to make it more complicated, the 'IONOS' offer is also displayed in the 'IONOS cloud' area :-(

**Comment by jbuchhammer** [comment]
@p-null : can we close this?

**Comment by p-null** [comment]
Thanks for clarifying! Close this now.

**Comment by p-null** [comment]
Hi @jbuchhammer , sorry to ping you here.
 
After reading some terraform docs and examples, I am interested in writing a 'IONOS' cloud server terraform provider. With that API document you provided, I think it's straightforward to write one.

Since I am not experienced with this, I would like to consult you first before doing it. 
Do you think it is feasible to implement a terraform provider for 'IONOS' cloud server provider? 
Are there any obstacles/tips/pitfalls you cloud foresee and would like to remind me of?  
Regarding the 'IONOS' Cloud Server API, could you point me to a developer that I can connect to if I have a question that I couldn't figure out?

Thanks very much.
