### ISSUE TITLE
Public attribute in K8s cluster unsupported

### ISSUE THREAD

**Issue by spralexx** [ionos-cloud/terraform-provider-ionoscloud#292]
When creating a ressource "ionoscloud_k8s_cluster" with an attribute "public" terraform throws 

│ Error: Unsupported argument
│ 
│   on main.tf line 69, in resource "ionoscloud_k8s_cluster" "XXXXXXX_k8s_cluster":
│   69:   public      = true
│ 
│ An argument named "public" is not expected here.

As it seams to be removed from the source please update the documentation and remove the public attribute.

**Comment by cristiGuranIonos** [comment]
Hi, thanks for creating this! I guess you're referring to the example [here](https://registry.terraform.io/providers/ionos-cloud/ionoscloud/latest/docs/resources/k8s_cluster). It will be removed from documentation.
