### ISSUE TITLE
Set PTR Record for Server 

### ISSUE THREAD

**Issue by dadevel** [ionos-cloud/terraform-provider-ionoscloud#315]
### Use-cases

I would like to configure a DNS pointer record for the public IP of my virtual server. At least I could not find any related documentation.

### Proposal

I think implementing a `ionoscloud_rnds` resource would be the correct way forward, provided a corresponding API endpoint exists for Ionos Cloud. See for example <https://registry.terraform.io/providers/hetznercloud/hcloud/latest/docs/resources/rdns>.

**Comment by cristiGuranIonos** [comment]
Thanks for raising this issue! We currently do not support this but it is on the roadmap. We will let you know once this is added.

**Comment by dadevel** [comment]
Unfortunate, but thanks for the quick response.

**Comment by cristiGuranIonos** [comment]
DNS support is now available in the latest tf release [here](https://github.com/ionos-cloud/terraform-provider-ionoscloud/releases/tag/v6.4.0).
