### ISSUE TITLE
[FR] import missing for some resources (v 5.2.1)

### ISSUE THREAD

**Issue by jbuchhammer** [ionos-cloud/terraform-provider-ionoscloud#39]
### Current Provider Version

```
v5.2.1 (and before)
```

### Use-cases
An import function is not implemented for
* volume
* group
* user
* share
* IPfailover
* loadbalancer

### Proposal

1.  At least for volume, group and user the import *must* be possible.
2.  IPFailover and share should be implemented too. However, due to the complex nature of these (e.g. patching an existing LAN) it might not be possible with Terraform or too much effort.
3.  The current loadbalancer is very restricted (and not relally recommended) and will have a much better successor in v6. It could be skipped.

**Comment by IuliaBlindu** [comment]
@jbuchhammer  please check v5.2.3
