### ISSUE TITLE
feat: Support state in ionoscloud_server to set the power state  

### ISSUE THREAD

**Issue by hegerdes** [ionos-cloud/terraform-provider-ionoscloud#412]
### Current Provider Version

```hcl
terraform {
  required_version = ">= 1.4.0"
  required_providers {
    ionoscloud = {
      source  = "ionos-cloud/ionoscloud"
      version = "6.4.1"
    }
    random = {
      source  = "hashicorp/random"
      version = "3.5.1"
    }
  }
}
```

### Use-cases

It would be awesome to support the `ionos_server_state`  prob to stop severs via terraform. The ansibe-modules support a `state` prob to set for each server. As far as I know there are the following states in the DCD:
 * running
 * shutdown
 * reset
This could also be used to reboot a server without having to connect to the server.

### Attempted Solutions

Currently this is not supported in this provider. You have to extract the server id form the state (or output the ids to a file) and make a extra api request in an arbitrary language 

### Proposal

Support the state prob in the `ionoscloud_server `

**Comment by cristiGuranIonos** [comment]
Thanks for raising this. We'll take a look at it.

**Comment by cbeti-ionos** [comment]
Support for modifying the power state for servers through the `vm_state` field should be available in the next release.

**Comment by hegerdes** [comment]
Nice to hear

**Comment by cristiGuranIonos** [comment]
Fixed in https://github.com/ionos-cloud/terraform-provider-ionoscloud/releases/tag/v6.4.10

**Comment by mitnicki** [comment]
also need this feature. foremost the reboot (reset) state.
Is the reset state also supported in the new provider version ?

**Comment by cristiGuranIonos** [comment]
Reboot is not supported yet. It is harder to implement in terraform due to how the concept of state works. This is because reboot is a transient state so we can't really measure if a reboot was done or not. 
I would suggest using ionosctl maybe to reboot a server: `ionosctl server reboot --datacenter-id DATACENTER_ID --server-id SERVER_ID`
