### ISSUE TITLE
Support creating a private K8s cluster using Terraform

### ISSUE THREAD

**Issue by mway-niels** [ionos-cloud/terraform-provider-ionoscloud#417]
This commit ([6d134d3](https://github.com/ionos-cloud/terraform-provider-ionoscloud/commit/6d134d37a29b867b1b29a130b8096cf857ea222e)) mentions removing the "public" option from the "ionoscloud_k8s_cluster" resource.

We are managing our infrastructure on IONOS using Terraform at the moment and are interested in testing a private K8s setup (behind a NAT gateway).

Could you elaborate the reasons for choosing to disable this feature in your Terraform provider? I understand private Kubernetes clusters are currently experimental, however we'd still like to test how it works and if it could be a good fit for our infrastructure in the future.

Please let me know if you require any further information.

Thank you. :)

**Comment by stefanjauker** [comment]
@cristiGuranIonos Do you have any ETA or timeline for the release date. This is important to us.

**Comment by cristiGuranIonos** [comment]
We think that in Q4 2023 private kubernetes would most likely be GA. It might be available earlier, but in EA.

**Comment by gthieleb** [comment]
Hi we have reached Q4/2023. Is this feature available? It would be great to connect the cluster API via a public facing loadbalancer because our helm deployment pipelines live behind a corporate proxy.

**Comment by cristiGuranIonos** [comment]
Should be added back in v6.4.12
