### ISSUE TITLE
Possibility to use a IONOS DCD User or Token with multiple contracts with Terraform

### ISSUE THREAD

**Issue by mitnicki** [ionos-cloud/terraform-provider-ionoscloud#451]
### Current Provider Version
Latest provider version

```
...
```

### Use-cases
Use a single user to deploy infrastructure into multiple contracts

### Proposal
Give us the possibility to set the Header X-Contract-ID as stated in the IONOS Cloud API reference within the IONOS Terraform-provider configuration

![image](https://github.com/ionos-cloud/terraform-provider-ionoscloud/assets/25565049/f66ca0af-0227-4d59-8951-667cf66f6bde)

**Comment by mitnicki** [comment]
Can you give me a timeframe when to expect the feature ? we need this feature for client-rollouts soon...

**Comment by cristiGuranIonos** [comment]
This will be configured globally using an env variable, is that Ok?

**Comment by mitnicki** [comment]
> This will be configured globally using an env variable, is that Ok?

We would need to set that as a tf-variable when triggering terraform runs by terraform API. So it would be great to have it as a normal terraform variable. I think that we are not able to set environment variables when triggering runs by terraform API for a workspace....

**Comment by cristiGuranIonos** [comment]
re-opening until release
