### ISSUE TITLE
IONOS_CONTRACT_NUMBER as Terraform variable

### ISSUE THREAD

**Issue by mitnicki** [ionos-cloud/terraform-provider-ionoscloud#460]
### Current Provider Version
newest provider

### Use-cases
start api-driven terraform runs for different subcontracts
Problem is that at the moment we cannot start terraform api driven workspace runs with parameters for environment variable.
API-Driven Terraform runs are only possible with Terraform VARs.

Would be great if you could give us the already existing IONOS_CONTRACT_NUMBER Environment variable as a Terraform Variable.

### Attempted Solutions
give us the possibility to set the contract id as a terraform variable instead of environment variable

### Proposal
would be great if we can configure the contract number in the ionos provider block of terraform

provider "ionoscloud" {
        username = "ionoscloud_username"
        password = "ionoscloud_password"
        endpoint = "ionoscloud_cloud_api_url"
        IONOS_CONTRACT_NUMBER = "contractnumberABC"
}

### References

https://developer.hashicorp.com/terraform/cloud-docs/api-docs/run

**Comment by cristiGuranIonos** [comment]
Should be fixed in https://github.com/ionos-cloud/terraform-provider-ionoscloud/releases/tag/v6.4.10
