### ISSUE TITLE
Typo in documentation of data ionoscloud_user/group

### ISSUE THREAD

**Issue by clemenschuaccso** [ionos-cloud/terraform-provider-ionoscloud#492]
## Description
In the documentation of data ionoscloud_user/group at the Attributes reference it says: The id of the LAN

## Expected behavior
It should say: The id of the user/group

## Environment

Provider version: 
```
6.4.10
```

## References
https://registry.terraform.io/providers/ionos-cloud/ionoscloud/latest/docs/data-sources/user
https://registry.terraform.io/providers/ionos-cloud/ionoscloud/latest/docs/data-sources/group

**Comment by cristiGuranIonos** [comment]
Thanks for creating this, indeed it is an issue. We also encourage contributions to the provider, as anyone can create a pull request.

**Comment by clemenschuaccso** [comment]
I created a PR for this: https://github.com/ionos-cloud/terraform-provider-ionoscloud/pull/493

**Comment by cristiGuranIonos** [comment]
Great, thanks!
