### ISSUE TITLE
NLB forwarding rule is missing proxyprotocol option	

### ISSUE THREAD

**Issue by LGLN-LS** [ionos-cloud/terraform-provider-ionoscloud#494]
### Current Provider Version
The DCD web interface and the Cloud API allow you to set the proxyProtocol option for an NLB forwarding rule. The Terraform provider lacks this function.

### Proposal
Add the proxyProtocol option.

### References
https://api.ionos.com/docs/cloud/v6/#tag/Network-Load-Balancers/operation/datacentersNetworkloadbalancersForwardingrulesPost

**Comment by mimihalescu** [comment]
Hello! Thank you for opening this issue! The proxy protocol implementation is in progress; we will update you once it is released.

CC: @cbeti-ionos

**Comment by cbeti-ionos** [comment]
Hi, the proxyProtocol parameter will be available for Terraform in the next release

**Comment by cristiGuranIonos** [comment]
Fixed in v6.4.11
