### ISSUE TITLE
Data Source k8s cluster `server` attribute

### ISSUE THREAD

**Issue by Fabii547** [ionos-cloud/terraform-provider-ionoscloud#537]
## Description
The [docs ](https://github.com/ionos-cloud/terraform-provider-ionoscloud/blob/5f13233e578b846ad890e8781e401b6a1bb61710/docs/data-sources/k8s_cluster.md?plain=1#L92) say that the k8s cluster data source should have an `server` attribute that should be the same as `config[0].clusters[0].cluster.server`. But this functionality was never implemented.

https://github.com/ionos-cloud/terraform-provider-ionoscloud/commit/cd7297cfd0a85ca9024531d7e13813a46f35d178 introduced the wrong documentation. 

The source code seems to support it, but lacks the server variable assignment: https://github.com/ionos-cloud/terraform-provider-ionoscloud/blob/5f13233e578b846ad890e8781e401b6a1bb61710/ionoscloud/data_source_k8s_cluster.go#L416-L418

## Expected behavior

Either remove the incomplete and never working implemention of the `server` attribute and update the documentation accordingly or make the `server` attribute work as described in the documentation.

**Comment by adeatcu-ionos** [comment]
Hello and thank you for raising this! I will take a look.

**Comment by cbeti-ionos** [comment]
> Either remove the incomplete and never working implemention of the `server` attribute and update the documentation accordingly or make the `server` attribute work as described in the documentation.

Seems the `server` value parsed from the kubeconfig was never set in the terraform state, we'll add a fix for it.
