### ISSUE TITLE
Retrieve grafana address from log pipeline

### ISSUE THREAD

**Issue by salyh** [ionos-cloud/terraform-provider-ionoscloud#556]
### Use-cases
I manage my logging pipeline with terraform but I am unable so far to retrieve the grafana url via terraform

### Attempted Solutions
Currently I use ionosctl for that in second step after terraform but I want to have a terraform only deployment model

### Proposal
Implement it as part of the output of the ionoscloud_logging_pipeline resource and/or data source

**Comment by adeatcu-ionos** [comment]
Hello and thank you for the suggestion! We will add this in the next release.

**Comment by cristiGuranIonos** [comment]
Should be fixed in latest release v6.4.18
