### ISSUE TITLE
Make clear in the documentation that a logging-pipeline only accepts tokens for authorization

### ISSUE THREAD

**Issue by jbuchhammer** [ionos-cloud/terraform-provider-ionoscloud#562]
In the documentation for logging_pipeline (docs/resources/logging_pipeline.md) it should be notified that only tokens are accepted for authorization.
It is already documented in the API and on the  docs page but if you go directly to logging_pipeline.md, that important info is missed.

An additional topic: Is it really still EA? If not, then the EA warning should be removed.

**Comment by adeatcu-ionos** [comment]
@jbuchhammer Thank you for raising this! I will solve these issues ASAP.
