### ISSUE TITLE
Terraform does not realise when logging_pipeline is ready

### ISSUE THREAD

**Issue by salyh** [ionos-cloud/terraform-provider-ionoscloud#584]
## Description
I try to create a logging pipeline via terraform.

```
resource "ionoscloud_logging_pipeline" "xxx" {
  name = "xxx"
  log {
    source   = "kubernetes"
    tag      = "kubernetes"
    protocol = "tcp"
    destinations {
      type              = "loki"
      retention_in_days = 30
    }
  }
}
```

After 8 minutes its still creating:

`ionoscloud_logging_pipeline.xxx: Still creating... [8m1s elapsed]`

but when I query the status via ionosctl the logging pipeline appears ready (see screenshot)

## Expected behavior
Terraform realise when logging pipeline is ready and continues to create other resources or exists with status code 0

## Environment

Terraform version: 
```
OpenTofu v1.7.2
```
Provider version: 
```
v6.4.17
```
OS:
```
```

<img width="334" alt="Monosnap ~ 2024-06-19 13-13-38" src="https://github.com/ionos-cloud/terraform-provider-ionoscloud/assets/3762447/afc88d2e-a18d-4e9c-82be-185acb469ab3">

```
$ ionosctl logging-service pipeline list
Id                                     Name         GrafanaAddress                                  CreatedDate
8f7xxxxx   XXX   grafana.xxxxxx.logging.xxxxx.ionos.com   2024-06-19T11:06:57Z
```

**Comment by salyh** [comment]
Looks like the `"state":` attribute is missing in the returned json?

**Comment by salyh** [comment]
Internal ticket ref 207171757

**Comment by salyh** [comment]
<img width="741" alt="Monosnap meod-control-plane – logging tf  meod-control-plane  2024-06-22 12-59-45" src="https://github.com/ionos-cloud/terraform-provider-ionoscloud/assets/3762447/d1b9604c-1db8-426c-b823-aca55a9ba44d">

**Comment by salyh** [comment]
https://github.com/ionos-cloud/sdk-go-logging/blob/4256f7f1ec700e40781f99943f0b3c280293a4fa/model_metadata.go#L31

For me it looks like it should be `json:"status,omitempty"` instead of `json:"state,omitempty"` to match `"status": "AVAILABLE"`

**Comment by adeatcu-ionos** [comment]
Hello! I will investigate this. Is it a long time between you noticing that the pipeline is `AVAILABLE` vs Terraform notifying you that the creation was successful? Maybe there is a small difference because of the ways in which the refresh calls are done in [this](https://github.com/ionos-cloud/terraform-provider-ionoscloud/blob/master/ionoscloud/resource_logging_pipeline.go#L96) function that basically handles the `wait for resource to become "AVAILABLE"` logic.

**Comment by adeatcu-ionos** [comment]
@salyh thank you for the clarification, I will take a look.

**Comment by cristiGuranIonos** [comment]
Hi, we have an issue opened with the logging team. Will be fixed asap.
