### ISSUE TITLE
arm_64 build required

### ISSUE THREAD

**Issue by ando47** [ionos-cloud/terraform-provider-ionoscloud#64]
Hello, could you please add a darwin_arm64 build for the provider? The new mac books are arm-based. Thanks, Ando

**Comment by mflorin** [comment]
Hello @ando47 , noted, we will include it in our next release.

**Comment by mflorin** [comment]
@ando47 , releases `v5.2.6` and `v6.0.0-beta.3` are now available for arm-based mac books as well.
