### ISSUE TITLE
Breaking change from 6.5.1 to 6.5.2 breaks ionoscloud_logging_pipeline resource

### ISSUE THREAD

**Issue by salyh** [ionos-cloud/terraform-provider-ionoscloud#661]
## Description
I noticed that there is a breaking change from 6.5.1 to 6.5.2. The ionoscloud_logging_pipeline resource now requires a mandatory `location? attribute as of 6.5.2 and this breaks current terraform scripts to fail with `vertex "ionoscloud_logging_pipeline.account" error: Missing required argument`

## Expected behavior
No breaking changes in minor or fix versions (respect semver, https://semver.org/)

## References
Introduced with https://github.com/ionos-cloud/terraform-provider-ionoscloud/pull/659

**Comment by cristiGuranIonos** [comment]
That is correct, we missed that one. We can revert the change. Alternatively, just adding location = "de/txl " will mean it will have the same behaviour as in v6.5.1. Terraform doesn't let us have default values for required fields we add.

**Comment by cristiGuranIonos** [comment]
Should be fixed in v6.5.3
