### ISSUE TITLE
{"httpStatus":403,"messages":[{"errorCode":"paas-feature-1","message":"feature is not enabled for the contract"}]}

### ISSUE THREAD

**Issue by PsyFrame** [ionos-cloud/terraform-provider-ionoscloud#667]
## Description
Up to version '6.4.19' - ionos-cloud/terraform-provider-ionoscloud - it works as expected. From version 6.5.0 and higher I receive the following error in connection with the creation (resource "ionoscloud_certificate" ...) and retrieval (data "ionoscloud_certificate" ...) of certificates (Certificate Manager):

**{"httpStatus":403,"messages":[{"errorCode":"paas-feature-1","message":"feature is not enabled for the contract"}]}**

## Expected behavior
Retrieving and creating certificates using the Certificate Manager.

## Environment

Terraform version: 
1.9.5

Provider version:
6.5.0 and higher

OS:
windows_amd64

## Configuration Files
...

## How to Reproduce
...

## Error and Debug Output
{"httpStatus":403,"messages":[{"errorCode":"paas-feature-1","message":"feature is not enabled for the contract"}]}

## Additional Notes
...

## References
...

**Comment by adeatcu-ionos** [comment]
Closing this since the problem was related to the API, not to the Terraform provider.
