### ISSUE TITLE
terraform-provider-ionoscloud_v6.6.1 plugin crashed

### ISSUE THREAD

**Issue by liwiatr** [ionos-cloud/terraform-provider-ionoscloud#699]
## Description

I tried setting up a Gitlab pipeline to create a simple server with terraform, but at the deploy stage I get an error saying that the terraform-provider-ionoscloud_v6.6.1 plugin crashed.

## Expected behavior

The datacenter, described in the main.tf should be created in the IONOS Datacenter Designer.

## Environment

Terraform version: 
```
Terraform v1.9.8
```
Provider version: 
```
6.6.1
```
OS:
```
Microsoft Windows 11 Pro
```

**Comment by digna-ionos** [comment]
It seems that your ssh_public_key variable is empty and that's why it's crashing. We will fix this to avoid crashing and return an error when that happens. Until that please check how you are setting that variable in your gitlab ci workflow
