### ISSUE TITLE
waiting for state change [VDC-5-0] unkonwn error occured

### ISSUE THREAD

**Issue by mosaickai** [ionos-cloud/terraform-provider-ionoscloud#702]
## Description
We get the following error since IONOS Updated their cube sizes:
**waiting for state change [VDC-5-0] unkonwn error occured**

## Expected behavior
The script should create a cube server from a snapshot

## Environment

Terraform version: 
```
1.9.8
```
Provider version: 
```
>= 6.4.18
```
OS:
```
Linux
```

## How to Reproduce

1. Have a snapshot of an "old" Cube S,M,L or XL
2. Create a terraform script to deploy a "new" cube server with the old snapshot.
3. Get the above error. waiting for state change [VDC-5-0] unkonwn error occured

## Error and Debug Output

waiting for state change [VDC-5-0] unkonwn error occured

## Additional Notes

No idea whether the issue is related to the old snapshots or not. If it is, it really shouldn't be though.

**Comment by cristiGuranIonos** [comment]
Hi, it's a known issue that should be fixed in a few days hopefully.
Not sure if that actually helps, but as a workaround:
"To avoid the bug, you can try to use snapshots for Physical Server, not DAS storages." 

We will let you know when the bug is fixed.

**Comment by mosaickai** [comment]
Thank you!
Would you mind linking the API issue thread, if there is one?

**Comment by cristiGuranIonos** [comment]
Cannot link as these are internal issues.
