### ISSUE TITLE
Updating nodepool values causes in-place upgrade

### ISSUE THREAD

**Issue by worldofgeese** [ionos-cloud/terraform-provider-ionoscloud#71]
## Description
Running `terraform apply` after updating nodepool specifications leads to an in-place upgrade of nodepool resources, which, according to Customer Care, is not supported by IONOS Cloud's managed kubernetes.

## Expected behavior
Changes to nodepool specifications should destroy the existing nodepool before recreating with new requested limits.

## Environment

Terraform version: 
```
v0.15.5
```
Provider version: 
```
6.0.0-beta.1
```
OS:
```
Fedora 32
```

## Configuration Files
```
# ---------------------------------------------------------------------------------------------------------------------
# SET TERRAFORM RUNTIME REQUIREMENTS
# ---------------------------------------------------------------------------------------------------------------------

terraform {
  required_version = ">= 0.12.26"

  required_providers {
    ionoscloud = {
      source  = "ionos-cloud/ionoscloud"
      version = "6.0.0-beta.1"
    }
  }
}


resource "ionoscloud_k8s_cluster" "this" {
  name        = var.cluster_name
  k8s_version = var.cluster_version
  maintenance_window {
    day_of_the_week = var.maintenance_day
    time            = var.maintenance_time
  }
}

resource "ionoscloud_k8s_node_pool" "this" {
  name        = var.cluster_name
  k8s_version = var.cluster_version
  auto_scaling {
    min_node_count = var.min_node_count
    max_node_count = var.max_node_count
  }

  maintenance_window {
    day_of_the_week = var.maintenance_day
    time            = var.maintenance_time
  }
  datacenter_id     = var.datacenter_id
  k8s_cluster_id    = ionoscloud_k8s_cluster.this.id
  cpu_family        = var.cpu_family
  availability_zone = var.availability_zone
  storage_type      = var.storage_type
  node_count        = var.node_count
  cores_count       = var.cores_count
  ram_size          = var.ram_size
  storage_size      = var.storage_size
}
```

## Output from `terraform apply`
https://gist.github.com/worldofgeese/20ecc5b2ab57b66507d887dbb9da5983

## Additional Notes
Please see Ticket#:20784952 for emails between myself and the IONOS Cloud Customer Care team.

**Comment by worldofgeese** [comment]
Hey folks, two issues in two days! I hope I'm not fast becoming the most unlikable customer of IONOS Cloud :pray:.

**Comment by worldofgeese** [comment]
Let me know if there's anything you need from me to close this issue

**Comment by IuliaBlindu** [comment]
@worldofgeese please check v6.0.0-beta.4

**Comment by IuliaBlindu** [comment]
@worldofgeese due to product strategy, starting from v6.0.0-beta.5, we removed the behavior you expected, and replaced it with the previous one. A workaround for you would be to rename the resource for it to be destroyed and recreated.

**Comment by worldofgeese** [comment]
Benjamin informed me today of the changed behavior. My workaround was to create two nodepools so if I need to respec one in CPU, memory, or storage, I will delete it via `terraform delete`, respec it, then recreate with a new `terraform apply`
