### ISSUE TITLE
Add ionoscloud_dataplatform_node_pool autoscaling configuration

### ISSUE THREAD

**Issue by lucabtg** [ionos-cloud/terraform-provider-ionoscloud#719]
### Current Provider Version

```
6.6.3
```

### Use-cases

Autoscaling is enabled for Dataplatform Node Pools in the IONOS DCD, however it can't be configured on infrastructure managed by terraform (ionoscloud_dataplatform_node_pool) at the moment.

### Attempted Solutions

/
### Proposal

ionoscloud_k8s_node_pool resources can be configured with autoscaling using the auto_scaling block and min_node_count/max_node_count arguments already, so we would expect the solution to look similar to this:
```
resource "ionoscloud_dataplatform_node_pool" "example" {
  ...
  auto_scaling {
    min_node_count = 1
    max_node_count = 2
  }
}
```

### References

/

**Comment by cristiGuranIonos** [comment]
Thanks, we will investigate.

**Comment by lucabtg** [comment]
Any updates on this already? 🙂 There seems to be no other way for us to use autoscaling in our dataplatform clusters currently.

**Comment by cristiGuranIonos** [comment]
We had some problems with the API, but we are currently no longer blocked so we have started work on the implementation.

**Comment by cristiGuranIonos** [comment]
should be fixed in https://github.com/ionos-cloud/terraform-provider-ionoscloud/releases/tag/v6.6.8. Please re-open if needed.
